# Site settings
name: DUSK Nighttiming Network Agency
title: DUSK Nighttiming Network Agency
description: Web design and development network.
email: info@justdusk.com
author:
  name: Eli Williamson
  email: eliwilliamson@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://justdusk.com" # the base hostname & protocol for your site
twitter_username: eliwilliamson
github_username:  eliwilliamson
exclude: [node_modules, gulpfile.js]

# Build settings
markdown: kramdown

# Publish posts with future date.
future: false

# Compile posts in the _drafts directory.
show_drafts: false

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: /projects/:title.html

# Publish posts with future date.
# _config.build.yml sets this to false on `gulp build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `gulp build`
show_drafts: false

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 10
paginate_path: 'page:num'